# Brain conditional model that maps ECoG data through an encoder into embeddings for
# the speech generator.

unconditional: false
in_channels: 1
out_channels: 1
diffusion_step_embed_dim_in: 128
diffusion_step_embed_dim_mid: 512
diffusion_step_embed_dim_out: 512
res_channels: 256
skip_channels: 256
num_res_layers: 36
dilation_cycle: 12
# NOTE This might be set differently depending on which dataset is being used
freeze_generator: true
pretrained_generator: /home/passch/exp/Uncond-PT-v8/checkpoint/250.pkl
encoder_config:
  name: brain_encoder
  c_in: 48
  c_mid: 96
  c_out: 128