# Brain + class-conditional model, i.e. a model whose speech generator has been pretrained
# using the class-conditional setting and is now being fine-tuned on brain data 

unconditional: false
in_channels: 1
out_channels: 1
diffusion_step_embed_dim_in: 128
diffusion_step_embed_dim_mid: 512
diffusion_step_embed_dim_out: 512
res_channels: 256
skip_channels: 256
num_res_layers: 36
dilation_cycle: 12
freeze_generator: true
pretrained_generator: /home/passch/exp/VariaNTSWords-CC-v2_h256_d36_T200_betaT0.02_L1000_cond/checkpoint/270.pkl
encoder_config:
  name: brain_class_encoder
  n_classes: 55
  c_mid: 64
  c_out: 128
  c_brain_in: 1600 # TODO Has to be adjusted to 1x48 electrodes for subj. 2 instead of 2x32 from subj. 1
