unconditional: false
in_channels: 1
out_channels: 1
diffusion_step_embed_dim_in: 128
diffusion_step_embed_dim_mid: 512
diffusion_step_embed_dim_out: 512
res_channels: 128
skip_channels: 256
num_res_layers: 30
dilation_cycle: 10
encoder_config:
  c_in: 2
  c_mid: 64
  c_out: 128
# pretrained_generator: /home/passch/exp/pretrain-generator-1_h256_d36_T20_betaT0.02_uncond/checkpoint/3.pkl