# Config file for the brain recording Harry Potter reading dataset

_name_: brain_conditional
splits_path: datasplits/HP1_ECoG_conditional/selected-electrodes_denoised/
audio_path: HP1_ECoG_conditional/selected-electrodes_denoised/
ecog_path: HP1_ECoG_conditional/selected-electrodes_denoised/
data_base_dir : /home/passch/data/
segment_length: 1000 # In milliseconds
sampling_rate: 16000 # audio sampling rate
sampling_rate_ecog: 100 # brain electrodes sampling rate
