# Fine-tuning dataset for HP ECoG data mapped to VariaNTS audio data

_name_: brain_cond_variants
splits_path: datasplits/VariaNTS/HP_55classes_90-10_b2s/
# splits_path: datasplits/VariaNTS/tiny_subset
audio_path: VariaNTS/VariaNTS_words_HP/
ecog_path: HP1_ECoG_conditional/sub-002/
ecog_splits_path: datasplits/HP1_ECoG_conditional/sub-002/
data_base_dir : data/
segment_length: 1000 # In milliseconds
sampling_rate: 16000 # audio sampling rate
sampling_rate_ecog: 100 # brain electrodes sampling rate
