# Config file for the brain recording Harry Potter reading dataset

_name_: hp1_ecog_conditional
splits_path: datasplits/HP1_ECoG_conditional/denoised_fixed-transcript_cleaned/
audio_path: HP1_ECoG_conditional/denoised_fixed-transcript_cleaned/
ecog_path: HP1_ECoG_conditional/denoised_fixed-transcript_cleaned/
data_base_dir : /home/passch/data/
segment_length: 1000 # In milliseconds
sampling_rate: 16000 # audio sampling rate
sampling_rate_ecog: 100 # brain electrodes sampling rate
