# Config file for the VariaNTS dataset loaded from a .csv file pointing to the 
# appropriate locations on disk.
# NOTE This is for debugging purposes only, as the tiny subset that is selected here only
# used 1.5% of the full VariaNTS words corpus, and the segment length is limited to 10k.
# This should be useful to quickly run training and inference and therefore see if the code
# works well. However, this will not produce good results

_name_: variants
data_path: /home/passch/thesis/datasplits/VariaNTS_Words/tiny_subset0.015-50-25-25
file_base_path: /data/julber/Dutch_spoken_datasets/VariaNTS corpus/
segment_length: 10000
sampling_rate: 44100