# Config file for the VariaNTS dataset loaded from a .csv file pointing to the 
# appropriate locations on disk

_name_: variants
data_path: /home/passch/thesis/datasplits/VariaNTS_Words/full_80-10-10
file_base_path: /data/julber/Dutch_spoken_datasets/VariaNTS corpus/
segment_length: 30000
sampling_rate: 44100

# The following percentiles for the VariaNTS word lengths may help in 
# choosing a segment length:
# 0.50    23322.00
# 0.70    26693.50
# 0.80    28860.40
# 0.84    30080.60
# 0.90    32187.00
# 0.95    35061.15
# 0.99    40267.10
# max     54195.00