# Config file for the VariaNTS dataset loaded from a .csv file pointing to the 
# appropriate locations on disk

_name_: variants
splits_path: /home/passch/data/datasplits/VariaNTS/HP_synth_sameval_aug_90-10/
data_path: /home/passch/data/VariaNTS/VariaNTS_words_16kHz_HP_synth_sameval_aug/
segment_length: 1000 # In milliseconds
sampling_rate: 16000
