# Config file for the VariaNTS dataset loaded from a .csv file, 

_name_: variants_brain
splits_path: datasplits/VariaNTS/HP_synth_sameval_aug2_cleaned_90-10/
audio_path: VariaNTS/VariaNTS_words_16kHz_HP_synth_sameval_aug2_cleaned/
eeg_path: HP1_EEG_conditional/denoised_fixed-transcript_cleaned/
data_base_dir : /home/passch/data/
segment_length: 1000 # In milliseconds
sampling_rate: 16000 # audio sampling rate
sampling_rate_eeg: 100 # brain electrodes sampling rate
