# Config file for the VariaNTS dataset loaded from a .csv file pointing to the 
# appropriate locations on disk.
# NOTE Uses tiny portion of the VariaNTS corpus and small segment length for
# debugging and testing purposes.

_name_: variants
splits_path: datasplits/VariaNTS/tiny_subset/
audio_path: VariaNTS/VariaNTS_words_16kHz_HP_synth_sameval_aug/
data_base_dir : /home/passch/data/
segment_length: 150 # In milliseconds
sampling_rate: 16000
