# Pre-training on the VariaNTS dataset, both unconditional and class-conditional.
# In the class conditional setting, conditional input will be created automatically
# from filenames and does not have to be specified here.

_name_: variants
splits_path: datasplits/VariaNTS/HP_55classes_90-10/
audio_path: VariaNTS/VariaNTS_words_HP/
data_base_dir : data/
segment_length: 1000 # In milliseconds
sampling_rate: 16000
targets: null #dag,heel,kan,keer,man,wel
