# Config file for the VariaNTS dataset loaded from a .csv file pointing to the 
# appropriate locations on disk

_name_: variants
splits_path: datasplits/VariaNTS/HP_synth_sameval_aug_90-10/
audio_path: VariaNTS/VariaNTS_words_16kHz_HP_synth_sameval_aug/
data_base_dir : /home/passch/data/
segment_length: 1000 # In milliseconds
sampling_rate: 16000
