defaults:
  - _self_
  - experiment: variants

train: # Not used in generate.py
  name: walltime-est # Name of experiment (prefix of experiment name)
  ckpt_epoch: max
  epochs_per_ckpt: 1
  iters_per_logging: 100
  n_epochs: 1
  learning_rate: 2e-4
  batch_size_per_gpu: 8

generate:
  ckpt_epoch: max # Which checkpoint to use; assign a number or "max". Is ignored when sampling during training
  n_samples: 4 # Number of utterances to be generated (per GPU)
  batch_size: null # Number of samples to generate at once per GPU. null means max (equal to samples_per_gpu)
  mel_path: null # Folder of preprocessed spectrograms (optional)
  mel_name: null # Name of specific spectrogram to condition on (set to null for unconditional, set to an audio file name for vocoding)

distributed:
  dist_backend: nccl
  dist_url: tcp://localhost:54321

wandb:
  mode: disabled # Pass in 'wandb.mode=online' to turn on wandb logging
  project: diffwave-dutch-unconditional
  entity: pascalschroeder
  id: null # Set to string to resume logging from run
  job_type: training
